# Coursera Data Science Capstone Project

This Notebook is used for Scraping Data of Neighborhoods in Canada on the wikipedia page.This is done as a part of the Capstone Project of the IBM Data Science Specialization on Coursera.

The wikipedia page used for scraping is: [Postal Codes of Canada](https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M)

The package used to scrape data is : [Beautiful Soup](https://beautiful-soup-4.readthedocs.io/en/latest/)

In [1]:
# requests package to get the html doc of a url
import requests

# Beautiful soup to Parse through the document
from bs4 import BeautifulSoup

import pandas as pd
import numpy as np

### Storing Data into a data frame

The following 3 cells are to store the data from the postal code table in the url to a dataframe by parsing with the help of Beautiul Soup Package.

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

#get the html of the url 
url_html = requests.get(url).text

In [3]:
#parsing the html doc from above
html_doc = BeautifulSoup(url_html, 'html.parser')

In [4]:
#postal code table
table = html_doc.table

#inititating an empty df
df = pd.DataFrame()

# reading the table into the empty Data frame
i = 0
for row in table.find_all('tr'):
    j = 0
    for col in row.find_all('td'):
        df.loc[i,j] = col.string.replace('\n','')
        j += 1
    i += 1

    
# changing col Names
column_headers = []
for th in table.find_all('th'):
    column_headers.append(th.string.replace('\n',''))

df.columns = column_headers
df

,Postal Code,Borough,Neighborhood
1,M1A,Not assigned,Not assigned
2,M2A,Not assigned,Not assigned
3,M3A,North York,Parkwoods
4,M4A,North York,Victoria Village
5,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
176,M5Z,Not assigned,Not assigned
177,M6Z,Not assigned,Not assigned
178,M7Z,Not assigned,Not assigned
179,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
180,M9Z,Not assigned,Not assigned

### Fromatting data frame
The following code cell is to modify the data frame we created in the above step into the required format of the assignment

In [7]:
# presenting the data in the required format
# editing the df created

#droping all Not Assigned Rows
df.drop(index = df[df['Borough'] == 'Not assigned'].index, axis = 0, inplace = True)

#grouping data based on Postal code then based on Borough and separating neighborhood values by ', '
df.groupby(['Postal Code','Borough'])['Neighborhood'].apply(', '.join).reset_index()
df

,Postal Code,Borough,Neighborhood
3,M3A,North York,Parkwoods
4,M4A,North York,Victoria Village
5,M5A,Downtown Toronto,"Regent Park, Harbourfront"
6,M6A,North York,"Lawrence Manor, Lawrence Heights"
7,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
161,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
166,M4Y,Downtown Toronto,Church and Wellesley
169,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
170,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
179,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [8]:
#displaying the shape of the data frame
df.shape

(103, 3)

**Author** : Nishchay Nagpal

**Email** : nishchaynagpal419@gmail.com

**Git Repository Link** : [Coursera_Capstone](https://github.com/Anima419/Coursera_Capstone)